### ISSUE TITLE
getSRAdbFile() error, cannot download file

### ISSUE THREAD

**Issue by jakeyeung** [seandavi/SRAdb#10]
Hello, I am unable to run the getSRAdbFile() function. It appears the 3 links to download the sqlite file are broken. 

```
srafile = getSRAdbFile()

trying URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'
Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) :
  cannot open URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'
```

The other urls also do not work
```
    url_sra_1 = "http://gbnci.abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz"
    url_sra_2 = "http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz"
    url_sra_3 = "http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz"
```

Thanks in advance.

Jake

**Comment by seandavi** [comment]
Can you give this a try again? I was able to use the first URL (which is now supposed to be pretty stable). If this doesn't work for you in R, can you try simply downloading using a browser?

**Comment by jakeyeung** [comment]
Downloading using a browser still gives me a 404 not found. It looks like others have the same problem (Issue #11).

**Comment by seandavi** [comment]
@jakeyeung, I am going to move this over to #11, so I'll close this one for now. If, once we get a solution in place you are still having problems, we can reopen this.

**Comment by modarzi** [comment]
Hi, 
I install SRAdb but when I  run  sqlfile <- getSRAdbFile() , I see below error:

Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) : 
  cannot open URL 'http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz'

I appricite if you guide me for solving this problem.
Best Regards,
Mohammad

**Comment by seandavi** [comment]
Hi, @modarzi. Upgrading R to at least version 3.4 and then reinstalling SRAdb should get things working again. Alternatively, you can download by hand using the links here:

https://github.com/seandavi/SRAdb/blob/master/README.md#raw-database-downloads

**Comment by modarzi** [comment]
Hi,@seandavi. I upgrade R to latest version but again I see below error:

Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) :
cannot open URL 'http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz'

For your second solution, is it possible to explain more.in other words which files should I download and how can I read it in my Rstudio?
Best Regards,
Mohammad

**Comment by seandavi** [comment]
You'll need to upgrade SRAdb also. 

```r
biocLite('SRAdb')
```

If that doesn't work, could you open a new issue and post the output of `sessionInfo()`? 

Sorry for the inconvenience.

**Comment by AIRibone** [comment]
Hi, same problem here

R 3.4

```
srafile=getSRAdbFile()
trying URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'
Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) :
  cannot open URL 'http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz'

```

**Comment by seandavi** [comment]
@AIRibone, could you post the output of sessionInfo() after loading SRAdb? In the meantime, the download link for SRAdb is on the README for this repo.

**Comment by Diwadkar** [comment]
I am having the same problem. 
<img width="924" alt="screen shot 2018-07-03 at 2 14 05 pm" src="https://user-images.githubusercontent.com/17258564/42237341-7dc284c0-7ecb-11e8-9231-3761c9269bd8.png">
<img width="906" alt="screen shot 2018-07-03 at 2 14 13 pm" src="https://user-images.githubusercontent.com/17258564/42237342-7dd298e2-7ecb-11e8-90df-86d57788cc41.png">

**Comment by AIRibone** [comment]
Hi!
I downloaded the SRAdb using `biocLite("SRAdb")`

```
> library(SRAdb)
Loading required package: RSQLite
Loading required package: graph
Loading required package: RCurl
Loading required package: bitops
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
>
>
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SRAdb_1.28.1    RCurl_1.95-4.10 bitops_1.0-6    graph_1.48.0   
[5] RSQLite_2.1.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17        XML_3.98-1.11       digest_0.6.15      
 [4] DBI_1.0.0           stats4_3.4.4        blob_1.1.1         
 [7] tools_3.4.4         bit64_0.9-7         Biobase_2.30.0     
[10] bit_1.1-14          parallel_3.4.4      compiler_3.4.4     
[13] BiocGenerics_0.16.1 memoise_1.1.0       GEOquery_2.36.0 
```

**Comment by Diwadkar** [comment]
Yes, it worked when I upgraded to R 3.4 and also updated biocLite(). Thank you!

**Comment by seandavi** [comment]
Awesome! Thanks for the patience....

**Comment by vpdesai2020** [comment]
> install.packages("SRAdb")
Installing package into ‘/home/desai/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘SRAdb’ is not available (for R version 3.4.4)

**Comment by seandavi** [comment]
@vpdesai2020, SRAdb is a Bioconductor package. 

```
install.packages("BiocManager")
BiocManager::install("SRAdb")
```

**Comment by maciematt** [comment]
Unfortunately, looks like this issue has made a return. I've just installed SRAdb, and tried running `srafile <- SRAdb::getSRAdbFile()` - here's the resulting error message:

```
> srafile <- SRAdb::getSRAdbFile() 
trying URL 'https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz' Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) :
    cannot open URL 'https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz'
> 
```

**Comment by kowshikasarker** [comment]
I installed SRAdb on MacOS and tried `getSRAdbFile()`, but it's not working.
`getSRAdbFile()
trying URL 'https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz'
Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) : 
  cannot open URL 'https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz'`

I tried to directly download from the following two links using `curl`, but none worked.

`curl https://s3.amazonaws.com/starbuck1/sradb/SRAmetadb.sqlite.gz
curl https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz`
