### ISSUE TITLE
No URLs working

### ISSUE THREAD

**Issue by saketkc** [seandavi/SRAdb#11]
```bash
wget -c https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz
--2017-09-11 14:54:00--  https://gbnci-abcc.ncifcrf.gov/backup/SRAmetadb.sqlite.gz
Resolving gbnci-abcc.ncifcrf.gov (gbnci-abcc.ncifcrf.gov)... 129.43.40.100
Connecting to gbnci-abcc.ncifcrf.gov (gbnci-abcc.ncifcrf.gov)|129.43.40.100|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-11 14:54:00 ERROR 404: Not Found.
```

```bash
 wget -c https://dl.dropboxusercontent.com/u/51653511/SRAmetadb.sqlite.gz
--2017-09-11 14:54:10--  https://dl.dropboxusercontent.com/u/51653511/SRAmetadb.sqlite.gz
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.2.6
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.2.6|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-11 14:54:10 ERROR 404: Not Found.

```

The last one times out:

```bash
wget -c http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
--2017-09-11 14:54:18--  http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
Resolving watson.nci.nih.gov (watson.nci.nih.gov)... 137.187.211.143
Connecting to watson.nci.nih.gov (watson.nci.nih.gov)|137.187.211.143|:80...
```

**Comment by markziemann** [comment]
I have the same problem.

**Comment by seandavi** [comment]
So, the process of updating the database is driven by a cron job. The database has gotten large enough that in some instances, the database is not completed building before the files are packaged for the website. We are working on a more robust solution, but the file is now available again. Sorry for the inconvenience. 

Just FYI, only the `gbnci` URL is expected to be "live". We will be adjusting those, also.

**Comment by saketkc** [comment]
Thanks @seandavi! Would it make sense to upload this on zenodo.org too (which will probably be more reliable)?

**Comment by seandavi** [comment]
The database is rebuilt about once per week or so and zenodo will want each "build" as a separate item, I think. The storage limit on zenodo is only 50GB, so it probably isn't a long-term solution.

There is one other detail--we have been asked in the past to remove old versions (due to a privacy issue), so we really want to have control over what remains "publicly" available to the extent possible.

**Comment by markziemann** [comment]
Thanks very much @seandavi

**Comment by keithforest** [comment]
Thanks @seandavi for maintaining this extremely useful package.

I am having the same problem, unable to access the url below.  

Is a fix expected any time soon?

```
 wget -c http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
--2017-09-20 13:53:09--  http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
Resolving watson.nci.nih.gov (watson.nci.nih.gov)... 137.187.211.143
Connecting to watson.nci.nih.gov (watson.nci.nih.gov)|137.187.211.143|:80... failed: Connection timed 
```out.
Retrying.

**Comment by seandavi** [comment]
@zhujack updated SRAdb in 278414cb to use an AWS S3 URL. Performance and stability downloads should be greatly improved. Version 1.36.0 (release) and 1.37.0 (devel) have both built successfully, so an update with `biocLite('SRAdb')` should get you the fix and AWS urls. Thanks for the patience.

**Comment by ngarud** [comment]
Hi! Having a similar problem. How do I download this? 

Below is the command in R for getting the file:

> sqlfile <<- getSRAdbFile()
trying URL 'http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz'
Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) : 
  cannot open URL 'http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz'

Here is the wget command:

-bash-4.2$ wget http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
--2017-12-27 16:14:29--  http://watson.nci.nih.gov/~zhujack/SRAmetadb.sqlite.gz
Resolving watson.nci.nih.gov (watson.nci.nih.gov)... 137.187.211.143
Connecting to watson.nci.nih.gov (watson.nci.nih.gov)|137.187.211.143|:80... failed: Connection timed out.
Retrying.

**Comment by saketkc** [comment]
@ngarud The files are now hosted on S3.
https://s3.amazonaws.com/starbuck1/sradb/SRAmetadb.sqlite.g

**Comment by seandavi** [comment]
Updating SRAdb will also do the trick, as the code has been changed as well.

**Comment by xinl22** [comment]
@saketkc I still find the original link doesn't work. What should I do after downloading file from S3 link?

**Comment by seandavi** [comment]
@xinl22, after gunzipping the file, it is the same SQLite file as before. You can connect to it as in the SRAdb vignette or use any other sqlite client to connect to it (R, python, etc.). If that explanation does not make sense, can you expand on where you are stuck and what you want to do? 

All that said, upgrading to the most recent version of the SRAdb R package is the way to go if you are using SRAdb from R.

**Comment by xinl22** [comment]
@seandavi  srafile = getSRAdbFile() failed due to the link issue so I download SRAmetadb.sqlite through S3 link. I saw your answer here https://www.biostars.org/p/93494/, so I hope to batch download SRA files. What should I do next?

**Comment by seandavi** [comment]
You can start from here:

```
con = dbConnect('SQLite',srafile)
```

The `srafile` is just the path and filename of the gunzipped sqlite file that you downloaded. From there, the process is the same as the biostars answer.

**Comment by xinl22** [comment]
@seandavi 

> srafile<-"/public/home/xinl22/SRAmetadb.sqlite"
> con = dbConnect('SQLite',srafile)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'dbConnect' for signature '"character"'

it seems that path is a character and dbConnect doesn't support it..
I run R on server. I don't know if I wrote the path in a wrong way

**Comment by seandavi** [comment]
Sorry. `dbConnect(RSQLite::SQLite(), srafile)`

**Comment by DanielAmsel** [comment]
The solution at : https://support.bioconductor.org/p/102481/  seems to work for me 
`system("wget https://s3.amazonaws.com/starbuck1/sradb/SRAmetadb.sqlite.gz")`
`system("gunzip SRAmetadb.sqlite.gz")`
`sqlfile <- 'SRAmetadb.sqlite'`

**Comment by benstory** [comment]
Hi is there any possibility of getting the code to generate/maintain these SRAmetadb's on our own?

**Comment by seandavi** [comment]
Not currently, no. Sorry.

**Comment by msevi** [comment]
Hi all,
It seems to me some columns of the tables for the current db are mostly empty as none of my queries return reasonable values, specifically the most recent entries appear to be incomplete.

The metadata associated with the SQLite database I've downloaded is as follows: 

schema version:     1.0                
creation timestamp: 2021-04-08 23:23:54

Does anyone have an older (working) version they're willing to share?

Kind regards,
Maria

**Comment by coraliegrattepanche** [comment]
Hi all,

obviously no url is updated with GEOmetadb, have you found a solution to keep the database up to date ?
Best

**Comment by zhujack** [comment]
Yes, the URL has been updated with GEOmetadb.

**Comment by coraliegrattepanche** [comment]
Hello, okay but when i'm using my script this url doesn't work ... http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb.sqlite.gz
Have you a solution ?
Best

**Comment by EasyPiPi** [comment]
Hi, I also meet the same problem,  

cannot open URL 'http://starbuck1.s3.amazonaws.com/sradb/GEOmetadb.sqlite.gz': HTTP status was '404 Not Found'

Is there an updated link?

Thanks,
Yixin

**Comment by thanhle7** [comment]
This might help: https://gbnci.cancer.gov/sra/SRAmetadb.sqlite.gz

**Comment by sumin5784** [comment]
Hi there,

I think lots of people are having similar issue like mines.

I have some questions for boty GEOmetadb, SRAdb.
1. How often they are update?
2. Why the link is not working for both GEOmetadb and SRAdb?
3. I think in one of the comment only gbnci server is live, but why I can't find some study using SRAdb (link wasn't working so I downloaded sqlite file directly from https://gbnci.cancer.gov/sra/)? For example, below is all I get from current SRAdb.

**col_desc         129
experiment       712
fastq            756
metaInfo           2
run              756
sample           278
sra              756
sra_ft           756
sra_ft_content   756
sra_ft_segdir      1
sra_ft_segments  186
study             31
submission        44** 

Does this mean there are only 31 studies in SRAdb sqlie file?

5. It seems like SRAdb does not cover all the samples in GEO, only covers very small studies? So, I'm trying to utilize GEOquery. Is there any efficient way to get all the sample info at once? Like, I want GSE, GSM, SRR, and all the sample meta together. But not sure where can I get the SRR along with GEO or GSM, hoping to extract all SRR id together so I can download fastq files using fastq-dump.


Thank you for the help in advance!
