### ISSUE TITLE
getSRAfile skip a file before completing downloading

### ISSUE THREAD

**Issue by xinl22** [seandavi/SRAdb#15]
getSRAfile('SRP057462',con,fileType='sra')

I'm using getSRAfile to download some sra files under the same project. It seems that R would start to download the next file before the previous file complete.

trying URL 'ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR198/SRR1981589/SRR1981589.sra'
ftp data connection made, file length 2627303688 bytes

downloaded 287.8 MB

trying URL 'ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR198/SRR1981600/SRR1981600.sra'
ftp data connection made, file length 1978085706 bytes

I know it could be the network issue, and I don't know if R would come back to finish the previous mission.  but is there any way to force this batch download finish one by one? Or is there an additional diameter serve as wget -c -t, to make it try again when faced a network issue?

Thanks

**Comment by seandavi** [comment]
You probably want to use `ascp` if possible. We should try to make this more robust, but `ascp`/aspera are designed for just this purpose. See section 3.6 of the vignette. Do let us know what you try and what works (or doesn't).

**Comment by xinl22** [comment]
@seandavi 

I tried with getSRAfile(c("SRR000658"),con,fileType='sra', srcType = 'fasp', ascpCMD = ascpCMD )

and it says:

Error in getSRAfile(c("SRR000658"), con, fileType = "sra", srcType = "fasp",  : 
  object 'ascpCMD' not found

Do I need to install ascp first?

**Comment by seandavi** [comment]
Yes, you'll need to install ascp and also define what the ascpCMD is for your location. You may need to get some help from a local administrator if you are on a cluster or shared workstation.

**Comment by xinl22** [comment]
@seandavi I've installed ascp and can download file through ascp, could you please tell me how to define ascpCMD for sraDB? Then I can see if I can finish by myself. We work on a CentOS server.

**Comment by seandavi** [comment]
You'll want to have ascpCMD look like what you type at the command line. From the vignette for SRAdb:

```
ascpCMD <-  'ascp -QT -l 300m -i /usr/local/aspera/connect/etc/asperaweb_id_dsa.putty'
```

You'll need to make sure that ascp is in the path or that you specify the whole path. You'll need to figure out where the identity file (asperaweb_id...) is on your system, also. That you got ascp working means that you likely have everything you need already.

**Comment by xinl22** [comment]
@seandavi It worked. Thanks.

**Comment by seandavi** [comment]
Awesome! Thanks for your patience.

**Comment by xinl22** [comment]
@seandavi 
I met another issue. 

getSRAfile(c("SRP034605"),con,fileType='sra', srcType = 'fasp', ascpCMD = ascpCMD)

after downloading one of sra file of this project. It says:

SRR1055083.sra                                                              100% 1159MB           - stalled -

so it won't move on. It won't automatically download the remaining SRA files in this project.

**Comment by seandavi** [comment]
Looks like the download stalled. I'm not sure what might have caused that. You could try again later. I don't think this has anything to do with SRAdb, though.

**Comment by xinl22** [comment]
@seandavi 

what confused me is the downloading of this file has finished and it stalled at 100%...

 I found when I tried to try again,  press Ctrl+C to terminate the current process, it says

"Session Stop  (Error: User aborted session)"

and then move on to download the next file... (problem seems to has been solved)
But the aim to use SRAdb is to automatically batch download all SRA files from a project. If it stalled, I have to manually press Ctrl+C to make it continue. This is not that convenient.

So I'm wondering if you could add some commands equals to pressing Ctrl+C to R script to make it continue to download the next file if stalled at 100%?

**Comment by seandavi** [comment]
I can look into making the download more robust, but SRAdb and R do not control ascp once that process is running, unfortunately. The better approach is to wrap the SRA access in R, but the SRA toolkit is pretty near impossible to do that with (I have tried). 

You could generate the download commands in R and then run them outside R if you want more control.

**Comment by xinl22** [comment]
@seandavi sorry I'm not very familiar with R programming.

I wrote a basic R script (SRAdownload.R):

library("SRAdb")
srafile ="/public/home/xinl22/SRA/SRAmetadb.sqlite"
con =dbConnect(RSQLite::SQLite(), srafile)
ascpCMD <-  'ascp -QT -l 300m -i ../asperaweb_id_dsa.openssh'
getSRAfile(c("SRP034605"),con,fileType='sra', srcType = 'fasp', ascpCMD = ascpCMD)

and then I can run it outside R.

Rscript SRAdownload.R

but I don't know how to control it. The aim is to control when "SRRxxxxxx.sra 100% xxxxMB - stalled -" appears, the program will automatically do something have the same effect as pressing ctrl+C(sorry I don't know how to express this through code). Is it possible to achieve this?  Thanks.
