### ISSUE TITLE
getSRAfile can't open URL to download

### ISSUE THREAD

**Issue by minwang90** [seandavi/SRAdb#16]
Hello,
I am trying to use SRAdb package to download a list of RNASeq data file without success. I would greatly appreciate any help. Here is one example:

> library('SRAdb');
> library('DBI');
> sqlfile <- getSRAdbFile()
> sql_con <- dbConnect(SQLite(), sqlfile);
> getFASTQinfo('SRR2660032', sql_con, srcType="ftp")
         run submission     study     sample experiment
1 SRR2660032  SRA303981 SRP011540 SRS1116004 SRX1339220
                                                                           ftp
1 ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR266/002/SRR2660032/SRR2660032.fastq.gz
> getSRAfile('SRR2660032', sqlcon, fileType='fastq', srcType="ftp");
Files are saved to:
'/NGS/SRA303981'
trying URL 'ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR266/002/SRR2660032/SRR2660032.fastq.gz'
Error in download.file(i, destfile = file.path(destDir, basename(i)),  :
  cannot open URL 'ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR266/002/SRR2660032/SRR2660032.fastq.gz'

I tried to download the sra fileType and got the similar error message. I checked the ftp site and did not find SRR2660032.fastq.gz file in the folder. Why is the file is listed in the SRAmetadb.sqlite metadata file but actually is not available for downloading?
Thanks.

**Comment by seandavi** [comment]
This SRA run is "controlled access." Therefore, the raw reads are not available for download. To gain access, you will need to use dbGaP to access the data:

https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=login

Hope that helps.

**Comment by minwang90** [comment]
Thanks Sean. I did not notice it is a controlled access data.

**Comment by seandavi** [comment]
No problem. When things don't work as expected, always good to check. We should put something in place to catch these instances. Just need to find the time....
