### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by wwood** [seandavi/SRAdb#17]
Hi,

I noticed that this SRA project has incomplete metadata in the SRAdb. On the SRA website, it suggests these samples are metagenomic, but that is not recorded in the SRAdb sqlite database. I get the feeling actually that this might be a specific instance of a more general problem, where newer samples do not have any metadata, but I'm not 100% sure on that.
```
sqlite> select * from sra where submission_accession='SRA631605';
4326356.0||||3977516.0||SRR6301447||2017-11-17|276317481.0|69554507266.0||||||3557847.0||SRX3402355||||||||||||||||||||||||||3161390.0||SRS2696339|||||||||123257.0||SRP125161|||||||||||777368.0|SRA631605|||||2018-05-24 18:09:52
4326357.0||||3977514.0||SRR6301445||2017-11-17|205866011.0|51806339560.0||||||3557849.0||SRX3402357||||||||||||||||||||||||||3161392.0||SRS2696341|||||||||123257.0||SRP125161|||||||||||777368.0|SRA631605|||||2018-05-24 18:09:52
4326358.0||||3977515.0||SRR6301446||2017-11-17|226134565.0|56825655314.0||||||3557848.0||SRX3402356||||||||||||||||||||||||||3161391.0||SRS2696340|||||||||123257.0||SRP125161|||||||||||777368.0|SRA631605|||||2018-05-24 18:09:52
4326359.0||||3977513.0||SRR6301444||2017-11-17|260375006.0|65506757180.0||||||3557850.0||SRX3402358||||||||||||||||||||||||||3161393.0||SRS2696342|||||||||123257.0||SRP125161|||||||||||777368.0|SRA631605|||||2018-05-24 18:09:52
```
Thanks again for making and maintaining such a useful piece of software. It forms a core part of my research.
ben

**Comment by seandavi** [comment]
Hi, @wwood. We have had some problems with maintainability of the current version of SRAdb. I have been working on an API-based replacement here:

https://api-omicidx.cancerdatasci.org/sra/1.0/ui/

I looked up the SRA project for one of the runs and found that it was, "SRP125161". Using that, I did a search using the "search" endpoint with entity "full", which returns SRR records with sample, study, and experiment info. Here is the URL, as an example:

https://api-omicidx.cancerdatasci.org/sra/1.0/search/full?q=study_accession%3ASRP125161&size=10

I'm very much looking for users and testers and do have the ability to modify or enhance the API, so feature requests are welcome. If you are an R user, the API client is available as SRAdbV2 (just github for now).

**Comment by wwood** [comment]
Ah, OK. Thanks for the quick reply. 

Looking at the API, I think it might not support the complex SQL query that I'm most interested in running. I actually do not use the R interface, but instead access the SQLite DB through a Ruby activerecord library I made for the purpose https://github.com/wwood/bioruby-sra. 

Then, I am looking for non-human metagenome datasets. It is something along the lines of this (excuse the Ruby code, but I imagine you follow):
```ruby
SRA.where(library_selection: 'RANDOM').where(library_source: 'METAGENOMIC').where(
      'instrument_model not like ?', '%Genome Analyzer%').where(
      'instrument_model like ?', '%Illumina%').where(
      'study_title not like ?','%human microbiome%')
```
Ideally I'd like to provide those constraints over the API and retrieve records as JSON. But this does not seem possible right now, is that right?

If I were only able to provide one constraint through the API, then I'd probably choose `library_source: METAGENOMIC`, retrieve all those records as JSON, and then filter those based on the other where clauses. However, I cannot see how to do this through the API, only a generic `search` is there AFAICS.

Can I ask what the difficulty is in maintaining the current implementation? Is there an SQLite DB on the back end still?

Thanks for your help. ben

**Comment by wwood** [comment]
Oh, I'm sorry, I see from https://github.com/seandavi/SRAdbV2 that more 'where' statements are indeed possible. I will check it out - ta.

**Comment by seandavi** [comment]
Definitely let me know what you think after trying out the API. There is not a SQLite DB on the backend; it is straight elasticsearch. However, I do have json dumps and can create a mongodb dump if that is desired by enough folks.

**Comment by seandavi** [comment]
I'm going to close here for now. The docs for querying using the API `q` field are described here:

https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

If you have more questions, can you drop on SRAdbV2?
