### ISSUE TITLE
SRAdbFile does not exist

### ISSUE THREAD

**Issue by iprada** [seandavi/SRAdb#18]
It seems that the dropbox file doe not exist anymore

> srafile = getSRAdbFile(method='wget')
--2018-06-12 17:20:29--  https://dl.dropboxusercontent.com/u/51653511/SRAmetadb.sqlite.gz
Resolving in... 10.20.0.50
Connecting to in|10.20.0.50|:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2018-06-12 17:20:30 ERROR 404: Not Found.

Error in download.file(url_sra, destfile = localfile, mode = "wb", method = method) : 
  'wget' call had nonzero exit status

**Comment by seandavi** [comment]
Hi, @iprada. The database file got too large to host on dropbox; we now host on AWS. You'll want to upgrade to a recent SRAdb version. That will fix the problem. Sorry for the inconvenience.
