### ISSUE TITLE
Update Frequency

### ISSUE THREAD

**Issue by saketkc** [seandavi/SRAdb#22]
Hi @seandavi,

What is the update frequency for the `SRAmetadb.sqlite`? It seems the `metaInfo's` `creation timestamp` does not necessarily reflect the sync status with SRA (and probably only reflects the time it was created).

I am trying to implement search features for [pysradb](https://github.com/saketkc/pysradb) and would like to list down its limitations.

Thanks!

**Comment by seandavi** [comment]
Sorry for the delay in replying. I have been working on a new approach that is more flexible than SRAdbV2 and SRAdb. For a preview, drop me an email (seandavi@gmail.com) and I'll forward you details. 

To reply to your question, SRAdb does not undergo a full refresh, but it is updated roughly once every few weeks. SRAdbV2 (actually, there is already a replacement) will be updated completely and regularly (about once per month--schedule to be pinned down).
