### ISSUE TITLE
Switch to httr for downloads

### ISSUE THREAD

**Issue by seandavi** [seandavi/SRAdb#5]
The download link for dropbox requires following a redirect.  This is the default for wget, but other download.file methods do not do so.  We should replace the download.file with something like:

``` r
r2 = GET('http://dl.dropbox.com/u/51653511/SRAmetadb.sqlite.gz',
  write_disk('SRAmetadb.sqlite.gz',overwrite=TRUE),
  progress())
```

**Comment by bharath-cchmc** [comment]
Is the SQLite file periodically updated? If so, could you please state the frequency of update?

**Comment by seandavi** [comment]
The redirect issue is now moot, as we are no longer using dropbox URLs. Everything comes directly from AWS s3 now as noted in fixing #11.
